[project]
name = "monkey-type-solver"
version = "0.1.0"
description = "Simple project for the Monkey Type typing test"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "loguru>=0.7.2",
    "ruff>=0.8.1",
    "selenium>=4.27.1",
]
